Models/Domain/BlogPost.cs
namespace Bloggie.WEB.Models.Domain
{
	public class BlogPost
	{
        public Guid Id { get; set; }

		public string Heading { get; set; }

		public string PageTitle { get; set; }

		public string Content { get; set; }

		public string ShortDescription { get; set; }

		public string FeaturedImageUrl { get; set; }

		public string UrlHandle { get; set; }

		public DateTime PublishDate { get; set; }

		public string Author { get; set; }	
		
		public bool Visible { get; set; }

		public ICollection<Tag> Tags { get; set; }

    }
}

Models/Domain/Tag.cs
namespace Bloggie.WEB.Models.Domain
{
	public class Tag
	{
		public Guid Id { get; set; }

		public string Name { get; set; }

		public string DisplayName { get; set; }


		public ICollection<BlogPost> BlogPosts { get; set; }

		



	}
}

Models/ErrorViewModel.cs
namespace Bloggie.WEB.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Models/ViewModels/AddTagRequest.cs
namespace Bloggie.WEB.Models.ViewModels
{
    public class AddTagRequest
    {
        public string  Name { get; set; }  
        
        public string DisplayName { get; set; }
    }
}

Models/ViewModels/EditTagRequest.cs
namespace Bloggie.WEB.Models.ViewModels
{
    public class EditTagRequest
    {

        public Guid Id { get; set; }

        public string Name { get; set; }

        public string DisplayName { get; set; }

    }
}

Controllers/AdminTagsController.cs
using Bloggie.WEB.Data;
using Bloggie.WEB.Models.Domain;
using Bloggie.WEB.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Bloggie.WEB.Controllers
{
	public class AdminTagsController : Controller
	{
		private readonly BloggieDbContext bloggieDbContext;

        public AdminTagsController(BloggieDbContext bloggieDbContext)
        {
           this.bloggieDbContext = bloggieDbContext;
        }


        [HttpGet]
		public IActionResult Add()
		{
			return View();
		}

		[HttpPost]
		[ActionName("Add")]
		public IActionResult Add(AddTagRequest addTagRequest)
		{
			var tag = new Tag
			{
				Name = addTagRequest.Name,
				DisplayName = addTagRequest.DisplayName,
			};

			bloggieDbContext.Tags.Add(tag);	
			bloggieDbContext.SaveChanges();

			return RedirectToAction("List");
		}

		[HttpGet]
		[ActionName("List")]
		public IActionResult List()
		{
			// use dbContext to read the tags
			var tags = bloggieDbContext.Tags.ToList();

			return View(tags);	
		}

		[HttpGet]
		public IActionResult Edit(Guid id) 

		{
			var tag = bloggieDbContext.Tags.FirstOrDefault(x => x.Id == id);

			if (tag != null) 
			{
				var editTagRequest = new EditTagRequest
				{
					Id = tag.Id,
					Name = tag.Name,
					DisplayName = tag.DisplayName,
				};

				return View(editTagRequest);
			}

			return View(null);
		}

		[HttpPost]
		public IActionResult Edit(EditTagRequest editTagRequest)
		{
			var tag = new Tag
			{
				Id = editTagRequest.Id,
				Name = editTagRequest.Name,
				DisplayName = editTagRequest.DisplayName,

			};

			var existingTag = bloggieDbContext.Tags.Find(tag.Id);

            if (existingTag !=null)
            {
				existingTag.Name = tag.Name;
				existingTag.DisplayName = tag.DisplayName;

				//save changes
				bloggieDbContext.SaveChanges();

				//show sucess notification
				return RedirectToAction("Edit", new { id = editTagRequest.Id });


            }
			//show error notification
			return RedirectToAction("Edit", new { id = editTagRequest.Id });
        }

		[HttpPost]
		public IActionResult Delete(EditTagRequest editTagRequest) 
		{
			var tag = bloggieDbContext.Tags.Find(editTagRequest.Id);

			if (tag != null) 
			{
			  bloggieDbContext.Tags.Remove(tag);
				bloggieDbContext.SaveChanges();

				//show a success notification
				return RedirectToAction("List");


			}

			//show an error notification
			return RedirectToAction("Edit", new {id = editTagRequest.Id});
		
		}
	}
}

Controllers/HomeController.cs
using Bloggie.WEB.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Bloggie.WEB.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Views/AdminTags/Add.cshtml
@model Bloggie.WEB.Models.ViewModels.AddTagRequest
@{
}

<div class="bg-secondary bg-opacity-10 py-2">

    <div class="container">

        <h1>Add new Tag - Admin Funcionality</h1>
    </div>
</div>

<div class="container py-5">
    <form method="post">
        <div class="mb-3">
            <label class="form-label">Name</label>
            <input type="text" class="form-control" id="name" asp-for="Name" />

        </div>

        <div class="mb-3">
            <label class="form-label">Display Name</label>
            <input type="text" class="form-control" id="displayName" asp-for="DisplayName" />

        </div>

        <div class="mb-3">

            <button type="submit" class="btn btn-dark" >Submit</button>
        </div>

    </form>

</div>

Views/AdminTags/Edit.cshtml
@model Bloggie.WEB.Models.ViewModels.EditTagRequest
@{
}

<div class="bg-secondary bg-opacity-10 py-2">

    <div class="container">

        <h1>Edit Tag - Admin Funcionality</h1>
    </div>
</div>

<div class="container py-5">
    <form method="post">
        <div class="mb-3">
            <label class="form-label">Id</label>
            <input type="text" id="id" class="form-control" asp-for="Id" readonly />

        </div>

        <div class="mb-3">
            <label class="form-label">Name</label>
            <input type="text" id="name" class="form-control"  asp-for="Name"/>

        </div>

        <div class="mb-3">
            <label class="form-label">Display Name</label>
            <input type="text" id="displayName" class="form-control" asp-for="DisplayName"/>

        </div>

        

        <div class="mb-3">

            <div class="d-flex">
                <button type="submit" class="btn btn-dark">Update</button>

                <button class="btn btn-danger ms-2" type="submit" asp-area="" 
                asp-controller="AdminTags" asp-action="Delete">Delete</button>

            </div>

           


        </div>

    </form>


</div>

Views/AdminTags/List.cshtml
@model List<Bloggie.WEB.Models.Domain.Tag>
@{
}

<div class="bg-secondary bg-opacity-10 py-2">

    <div class="container">

        <h1>Show All Tags - Admin Funcionality</h1>
    </div>
</div>

<div class="container py-5">

    @if (Model != null && Model.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Display Name</th>
                    <th></th>
                </tr>

            </thead>
            <tbody>
                @foreach (var tag in Model)
                {
                    <tr>
                        <td>@tag.Id</td>
                        <td>@tag.Name</td>
                        <td>@tag.DisplayName</td>
                        <td>
                            <a asp-area="" asp-controller="AdminTags" asp-action="Edit" asp-route-id="@tag.Id">Edit</a>
                        </td>

                    </tr>
                }

            </tbody>

        </table>
    }
    else
    {
        <p>No tags Found</p>
    }

</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Bloggie.WEB</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Bloggie.WEB.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow ">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bloggie.WEB</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>

						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
								Admin
							</a>
							<ul class="dropdown-menu">
								<li>
									<a class="dropdown-item" asp-area=""
									   asp-controller="AdminTags" asp-action="Add">Add Tag</a>
								</li>
								<li>
									<a class="dropdown-item" asp-area=""
									   asp-controller="AdminTags" asp-action="List">show All Tags</a>
								</li>





							</ul>
						</li>
						
							
								
							
						

					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div>
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2024 - Bloggie.WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>